config/routes.rb
Rails.application.routes.draw do
  resources :locations
  root 'welcome#index'

  get "/pages/:page" => "pages#show"
    resources :articles
  resources :pages

  get "/search" => "locations#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/models/location.rb
class Location < ApplicationRecord
   #def self.search(search)
    #where("name ILIKE ? OR ingredients ILIKE ? OR cooking_instructions ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  #end
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
     @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
      @location = Location.find(params[:id])
  end

  def search
      @locations = Location.where('name LIKE ?', "%#{params[:searchitem]}%") | Location.where('location LIKE ?', "%#{params[:searchitem]}%") #| Location.where('description like ?', "%#{params[:name]}%")
    #@locations = Location.where(name: params[:name]) | Location.where(location: params[:name]) | Location.where(description: params[:name])
    #@locations = Location.where('name OR location OR description LIKE ?', "%#{params[:name]}%")

  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :description, :price, :pricemonth, :location, :openingtime, :closingtime, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end

  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb

<div class="margin"></div>

<h1>Edit article</h1>

<%= render 'form' %>

<div class="margin2"></div>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb

  <div class="margin"></div>

  <h1>Blog</h1>

  <div class="margin2"></div>



<table>

  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure about this?' } %></td>
  </tr>
  <% end %>
</table>

<div class="margin2"></div>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb

<div class="margin"></div>

<h1>New article</h1>

<%= render 'form' %>

<div class="margin2"></div>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb

<div class="margin"></div>

<h1>Blog article</h1>

<div class="margin2"></div>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<div class="margin2"></div>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flexplore</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <!-- Mogelijk moet CSS after bootstrap? <link rel="stylesheet" href="css/application.css.scss">-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <!-- Voor hoogte en breedte kun je ook gebruiken:
            <%= image_tag ("logo.png"), height: 'auto', width: '100' %>, -->
            <a class="navbar-brand" href="/">
              <%= image_tag "logo.png", class: "img-responsive", class: "style_logo", title: "Flexplore logo" %>
            </a>

          </div>

          <div class="collapse navbar-collapse" id=".navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Home</a></li>
              <li class="active"><a href="/pages/how-it-works">How It Works</a></li>
              <li class="active"><a href="/locations">Locations</a></li>
              <li class="active"><a href="/pages/about">About Us</a></li>
              <li class="active"><a href="/articles">Blog</a></li>
              <li class="active"><a href="/pages/contact">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
            <form class="navbar-form navbar-right">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
              </div>
            </form>

        </div>
      </div>
    </nav>

      <div class="container">
        <%= yield %>
      </div>

<br />

  <div id="footer">
    <div class="container">
      <i>&copy; <%= Time.now.year %> Michelle Lau | All Rights Reserved</i>
    </div>
  </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :location_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :location_description %>
  </div>

  <div class="field">
    <%= form.label :price, "Price per day in €" %>
    <%= form.text_field :price, id: :location_price %>
  </div>

  <div class="field">
  <%= form.label :pricemonth, "Price per month in €" %>
  <%= form.text_field :pricemonth, id: :location_pricemonth %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :location_location %>
  </div>

  <div class="field">
    <%= form.label :openingtime, "Open" %>
    <%= form.time_select :openingtime, id: :location_openingtime %>
  </div>

  <div class="field">
    <%= form.label :closingtime, "Close" %>
    <%= form.time_select :closingtime, id: :location_closingtime %>
  </div>

  <div class="field">
  <%= form.label :picture %>
  <%= form.file_field :picture, id: :location_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<div class="margin"></div>

<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="margin"></div>

  <h1>Locations</h1>

  <div class="margin2"></div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price per day in €</th>
     <th>Price per month in €</th>
    <!-- <th>E-mail</th>-->
    <!-- <th>Phone number</th>-->
      <th>Location</th>
      <!-- <th>City</th>-->
      <th>Open</th>
      <th>Close</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.description %></td>
        <td><%= location.price %></td>
        <td><%= location.pricemonth %></td>
        <td><%= location.location %></td>
        <td><%= location.openingtime.to_s (:time) %></td>
        <td><%= location.closingtime.to_s (:time) %></td>

        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<div class="margin"></div>

<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/search.html.erb
<p id="notice"><%= notice %></p>

<div class="margin"></div>

<h1>Locations</h1>

<div class="margin2"></div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price per day in €</th>
      <th>Price per month in €</th>
      <th>Location</th>
      <th>Open</th>
      <th>Close</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.description %></td>
        <td><%= location.price %></td>
        <td><%= location.pricemonth %></td>
        <td><%= location.location %></td>
        <td><%= location.openingtime.to_s (:time) %></td>
        <td><%= location.closingtime.to_s (:time) %></td>
        <!--Door de volgende syntax krijg ik een "ActionView::Template::Error (undefined method `picture' for nil:NilClass" error. De syntax moet overigens wel worden afgesloten met %>. Daar kon ik geen comment van maken.)-->
        <%-#<%= image_tag(@location.picture, height: 50) if @location.picture.present? %>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="margin"></div>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<p>
  <strong>Price per day in €:</strong>
  <%= @location.price %>
</p>

<p>
  <strong>Price per month in €:</strong>
  <%= @location.pricemonth %>
</p>

<p>
  <strong>Location:</strong>
  <%= @location.location %>
</p>

<p>
  <strong>Open:</strong>
  <%= @location.openingtime.to_s (:time) %>
</p>

<p>
  <strong>Close:</strong>
  <%= @location.closingtime.to_s (:time) %>
</p>

<p>
  <strong>Picture:</strong>
  <!--<%= @location.picture %>-->
  <br />
  <br />
  <%= image_tag(@location.picture, height: 250) if @location.picture.present? %>
  <!--<img src="/images/42-workspace-bureau.jpg" height="200px">-->
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>Flexplore</title>
 </head>

  <div class="margin"></div>

 <body>
   <div class="head">
     <h1>About Us</h1>

     <div class="margin2"></div>
     <div class="container-options">

     Founded in Rotterdam, The Netherlands in 2017, Flexplore is a growing marketplace for companies to list available workspaces and for people to find their ideal flexible workspace.

     <h2>Vision</h2>
       <p1>We want to create a social platform where people and companies can meet and interact.</p1>

       <br/>

       <h2>Mission</h2>
       <p1>We offer people and companies the opportunity to find each other.</p1>

     </div>
   </div>
 </body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Flexplore</title>
</head>

  <div class="margin"></div>

<body>

  <div class="head">
    <h1>Contact</h1>

    <div class="margin2"></div>
    <div class="container-options">

    <h2>Address</h2>

    <p1>
      Flexplore B.V.<br>
      Hoofdstraat 100<br>
      3000 ML Rotterdam<br>
      The Netherlands<br>
      +31 (0) 10-1234567<br>
      info@flexplore.nl<br>
      http://www.flexplore.nl
    </p1>


    <h2>Company registration</h2>

    <p1>
      Kamer van Koophandel Rotterdam<br>
      File number 01234567<br>
      VAT registration number NL000000
    </p1>

    </div>
  </div

</body>
</html>

app/views/pages/how-it-works.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flexplore</title>
</head>

  <div class="margin"></div>

<body>

  <div class="head">
    <h1>How It Works</h1>

    <div class="margin2"></div>
    <div class="container-options">

    <h2>List your workspace</h2>
    <p1>Create a professional location page in minutes. Reach audience in seconds.</p1>

    <h2>Find a workspace</h2>
    <p1>You search, find, book and work anywhere in the world.</p1>

    <div class="margin2"></div>

    <p1>Soon we will provide you more information about our services.</p1>

    </div>
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
<!--VANAF HIER Z CODES BOOTSTRAP-->

  <title>Flexplore: find flexible workspaces</title>

</head>

<div class="margin-home"></div>

<body class="site-home">
  <!--<h1>Flexplore</h1>-->

<h1>Find your favourite workspace</h1>

<div class="site-search">
  <form action="/search" method="GET">
    <input type="text" name="searchitem" placeholder="Search name or city"/>
    <input type="submit" value="Search">
  </form>
</div>

<!--<%= form_tag(locations_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search name or city" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>-->

 <br />
<div class="container-options">

<div class="site-options">
  <form>
    <p><input type="radio" name="price" value="day"> Price per day:<br/>

      <input type="checkbox" name="price" value="first"> 0 - 10 <br>
      <input type="checkbox" name="price" value="second"> 10 - 20 <br>
      <input type="checkbox" name="price" value="third"> 20 - 30 <br>
      <input type="checkbox" name="price" value="fourth"> 30 - 40 <br>
      <input type="checkbox" name="price" value="fifth"> 40+ <br></p>

  </form>
</div>

<div class="site-options">
  <form>
      <p><input type="radio" name="price" value="month" checked> Price per month:<br>

        <input type="checkbox" name="price" value="one"> 0 - 50 <br>
        <input type="checkbox" name="price" value="two"> 50 - 100 <br>
        <input type="checkbox" name="price" value="three"> 100 - 150 <br>
        <input type="checkbox" name="price" value="four"> 150 - 200 <br>
        <input type="checkbox" name="price" value="five"> 200 - 250 <br>
        <input type="checkbox" name="price" value="six"> 250+</p>
  </form>
</div>

<div class="site-options">
  <form>
      <p>Facilities:<br/>

        <input type="checkbox" name="facilities" value="wifi"> Free WiFi<br>
        <input type="checkbox" name="facilities" value="cofee"> Coffee/tea<br>
        <input type="checkbox" name="facilities" value="kitchen"> Kitchen<br>
        <input type="checkbox" name="facilities" value="printer"> Printer<br>
        <input type="checkbox" name="facilities" value="copy"> Copy machine<br></p>
 </form>
</div>

<div class="site-options">
 <form>
   <p>Extra:<br/>
     <input type="checkbox" name="extra" value="evening"> Open after 18:00<br>
     <input type="checkbox" name="extra" value="saturday"> Open on Saturday<br>
     <input type="checkbox" name="extra" value="sunday"> Open on Sunday<br></p>
 </form>
</div>

</div>

<!--HIER EINDIGT CODE Z-->

<h2>Under construction</h2>
<h2>Under construction</h2>
<h2>Under construction</h2>
<h2>Under construction</h2>
<h2>Under construction</h2>
<h2>Under construction</h2>


<h2>More information soon</h2>
<h2>More information soon</h2>
<h2>More information soon</h2>
<h2>More information soon</h2>
<h2>More information soon</h2>

</body>
 </html>


<!--<%= link_to 'Blog', controller: 'articles' %>-->